name = "julia_try2_package"
uuid = "46c5c98e-ee98-4e77-a7c9-5cc9fd1967ff"
authors = ["Hasan Alshammari"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
